/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jsonParserAyzek;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        Main_JSON_Parser classUnderTest = new Main_JSON_Parser();
    }
}
