/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.tishenko;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TsonTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Tson classUnderTest = new Tson();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
